### ISSUE TITLE
Potentially problem with county

### ISSUE THREAD

**Issue by LemmaLegal** [nonprofittechy/docassemble-MOHUDEvictionProject#100]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `custom error action`
Details | 1. Began section on Information about your rental agreement
2. Inputted address / party information 
3. Selected "no" for answers about unfair deception / foreclosure related to the property 
4. A bug icon populated on the screen and alerted me that "something went wrong" Website prompted me to go back to the previous screens.
Variable being sought | `al_custom_error_action`
Package version | `1.0`
Maturity target | Level 2 - this needs to be fixed to meet expectations of a basic intake
Filename | `docassemble.MOHUDEvictionProject:data/questions/MOHUDEvictionProject.yml`

**Comment by tobyfey** [comment]
I am guessing that this is related to a problem with county, because that's where this would happen

**Comment by tobyfey** [comment]
Replicated it when I used Saint Louis as the city

fixed that by changing to this in id: county information
elif users[0].address.city in ["St. Louis","Saint Louis"]:

**Comment by tobyfey** [comment]
I think i should move the information in id: county_information to be determined right after address.  It would make it easier for testing, and obvious when a problem arises.

added to id: interview_order_eviction_motion_to_continue
  users[0].address.address
  users[0].address.geocode()
  trial_court_name_default

**Comment by tobyfey** [comment]
It broke again in city of St. Louis, because it was searching for docket_available, and when it went back to that code block, now users[0].address.county is set, so it goes into the first part of the if statement which caused the error.

I added to id: county information
  if hasattr(users[0].address,"county") and not users[0].address.county == "City of St Louis":

**Comment by nonprofittechy** [comment]
Need to use `users[0].normalized_address()` before **every** place we look up and use the address attributes for logic.

E.g., `users[0].normalized_address().county`.

Note: `users[0].normalized_address().county` is equal to "City of St Louis" when the user lives in the city of St Louis (Even though it's not technically a county).

**Comment by tobyfey** [comment]
`users[0].normalized_address().county` was being set to "City of St Louis" by the line I had in there -     `users[0].address.norm_long.county = "City of St Louis"`

I removed that and users[0].normalized_address().county is not set

**Comment by tobyfey** [comment]
What do we need the name of the county for?  We need to use the county name from the geocoded address as the key in the county_to_circuit dictionary to get a circuit number.  We could use the circuit number for any conditional logic based on the county.

**Comment by nonprofittechy** [comment]
Description of the problem: when the user is in the city of st louis, there's no county attribute set in the normalized address. We need some way to set it manually.

Idea: we rely directly on the `trial_court` object and its attributes instead. We define `trial_court` so it accounts for whatever information is actually defined on the users[0].normalized_address().county / city.

1200 Market St, St Louis, MO is an easy test address to use. (City Hall)

**Comment by nonprofittechy** [comment]
Also: refactor the court logic into its own YAML file (for future reuse)
