### ISSUE TITLE
Don't ask "are there additional hearings". Directly ask "did your eviction hearing date pass?" (or better version of language)

### ISSUE THREAD

**Issue by LemmaLegal** [nonprofittechy/docassemble-MOHUDEvictionProject#101]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `custom error action`
Details | 1. Began completing Using Case.Net section. 
2. When the prompt asked me if the court had held any additional hearings, I said yes instead of no, but the response still asked me when the eviction hearing was scheduled for. 
Suggestion: allow for / add a section about default judgments. If no hearing is upcoming because a tenant received a default judgment on their case, then this section might lead them to believe that there is another hearing to be held rather than alerting them to the need to schedule their own motion to set aside hearing.
Variable being sought | `al_custom_error_action`
Package version | `1.0`
Maturity target | Level 3 - this needs to be fixed to meet expectations of a sophisticated intake worker
Filename | `docassemble.MOHUDEvictionProject:data/questions/MOHUDEvictionProject.yml`

**Comment by tobyfey** [comment]
https://github.com/nonprofittechy/docassemble-MOHUDEvictionProject/issues/83

**Comment by tobyfey** [comment]
On previous page I put in a past date for the date of the hearing in an effort to represent a situation where the tenant had a default judgment entered against them. Might be helpful to elaborate on this more and advise tenant to contact court to confirm whether a default judgment was entered. If so, perhaps it can generate a motion to set aside or direct the tenant to the blank motion to set aside.

**Comment by nonprofittechy** [comment]
We kind of landed on:

Don't ask about the additional hearings if it's not relevant. Instead, just ask if the date for the eviction hearing has passed. We can have "help" information that lets them use the docket to verify, but only if they don't know the answer about the eviction hearing passing or not.

**Comment by tobyfey** [comment]
Removed past_hearings from id: docket_review_order

past_hearings isn't used by any interview or document
