### ISSUE TITLE
Create a Bootstrap theme

### ISSUE THREAD

**Issue by nonprofittechy** [nonprofittechy/docassemble-MOHUDEvictionProject#11]

**Comment by nonprofittechy** [comment]
@miabonardi is this one you can take?

Need to confirm colors with Jessica Hicklin

**Comment by miabonardi** [comment]
$white: #ffffff;

$theme-colors: (
    "light":      #ffffff,
    "dark":       #00284a,
    "primary":    #00284a,
    "secondary":  #ff603e,
    "info":       #79879a,
    "success":    #009f58,
    "warning":    #e2c900,
    "danger":     #f10c00,
);

**Comment by nonprofittechy** [comment]
![DALL·E 2022-11-13 21 43 33 - logo for a housing resources website in a commercial style](https://user-images.githubusercontent.com/7645641/220697163-80fbaada-6285-4b60-924e-c501e74c847a.png)
