### ISSUE TITLE
ID explain other case net uses: 
User feedback: something
(`docket_review_conclusion`)

### ISSUE THREAD

**Issue by LemmaLegal** [nonprofittechy/docassemble-MOHUDEvictionProject#110]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `explain other case net uses`
Details | On previous page I put in a past date for the date of the hearing in an effort to represent a situation where the tenant had a default judgment entered against them. Might be helpful to elaborate on this more and advise tenant to contact court to confirm whether a default judgment was entered. If so, perhaps it can generate a motion to set aside or direct the tenant to the blank motion to set aside.
Variable being sought | `docket_review_conclusion`
Package version | `1.0`
Maturity target | Level 2 - this needs to be fixed to meet expectations of a basic intake
Filename | `docassemble.MOHUDEvictionProject:data/questions/MOHUDEvictionProject.yml`

**Comment by tobyfey** [comment]
Closed as duplicate, comment added to other issue
