### ISSUE TITLE
Add instructions about cell phones

### ISSUE THREAD

**Issue by LemmaLegal** [nonprofittechy/docassemble-MOHUDEvictionProject#111]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `download eviction_defender`
Details | We have a couple of courts that will not allow a tenant to bring their cell phone in without prior approval from the court. In the instructions for the tenant, it might be helpful to advise tenants to contact the court to see if there are any special requirements if they intend to use their cell phone to show the judge photos of other documentation.
Variable being sought | `eviction_defender_download`
Package version | `1.0`
Maturity target | Level 4 - this is purely an enhancement to improve user experience
Filename | `docassemble.MOHUDEvictionProject:data/questions/MOHUDEvictionProject.yml`

**Comment by ianeis** [comment]
Added: `warning_ic.append("Some courts do not allow tenants to bring their cell phone without prior approval. If you intend to use your cell phone to show the judge photos or other documentation, you should contact the court to see if there are any special requirements.")`
