### ISSUE TITLE
Update Terms of Use and remove MA references

### ISSUE THREAD

**Issue by tobyfey** [nonprofittechy/docassemble-MOHUDEvictionProject#112]
Terms of Use need to be updated. Many references to MA.

**Comment by nonprofittechy** [comment]
For the modern way to do this, see https://github.com/nonprofittechy/docassemble-HousingCodeChecklist/blob/fa54f6bc11776eb0490f211b7a30b85016d93d26/docassemble/HousingCodeChecklist/data/questions/housing_code_interview.yml#L335

and https://github.com/nonprofittechy/docassemble-HousingCodeChecklist/blob/main/docassemble/HousingCodeChecklist/data/questions/feedback.yml

**Comment by ianeis** [comment]
Update organization names, not just state name

**Comment by ianeis** [comment]
Make terms of use inline, not other website

**Comment by ianeis** [comment]
Pushed to working branch

**Comment by ianeis** [comment]
closing issue now but still on working branch
