### ISSUE TITLE
Error screen when specifying you do not want to use Case.net

### ISSUE THREAD

**Issue by ianeis** [nonprofittechy/docassemble-MOHUDEvictionProject#125]
Was speeding through interview so I don't remember all my answers. Appeared immediately after screen `id: eviction hearing date if docket available`. Before that, I had selected No when asked if I wanted to use Case.net.

I pressed Undo a few times and selected Yes, I wanted to use Case.net (on `id: Docket_introduction`) and was able to proceed past `id: eviction hearing date if docket available` without errors.

[error.pdf](https://github.com/nonprofittechy/docassemble-MOHUDEvictionProject/files/10825903/error.pdf)

**Comment by tobyfey** [comment]
couldn't replicate this, but I think the problem may arise when the petition isn't available.

**Comment by tobyfey** [comment]
Nope, that wasn't it, and the order of the question makes it seem like it would only happen with petition_available.
