### ISSUE TITLE
`id: sale of property` error screen when answering Yes to first question

### ISSUE THREAD

**Issue by ianeis** [nonprofittechy/docassemble-MOHUDEvictionProject#127]
`id: sale of property`

When answering `Yes` to the first question error screen appears to be unavoidable no matter what configuration of the followup questions I answer.

Error screen always ends with `Needed definition of notice_of_sale_provided`. Example error screen attached.

[error3.pdf](https://github.com/nonprofittechy/docassemble-MOHUDEvictionProject/files/10826627/error3.pdf)

**Comment by tobyfey** [comment]
This is fixed now, notice_of_sale_provided has been replaced by notice_of_sale_provided_new_landlord throughout interview and documents.
