### ISSUE TITLE
Write "next steps" instructions for the user

### ISSUE THREAD

**Issue by nonprofittechy** [nonprofittechy/docassemble-MOHUDEvictionProject#13]

**Comment by nonprofittechy** [comment]
Lemma Legal to make first draft of these

**Comment by nonprofittechy** [comment]
Next steps document from MADE (but note that the design of this is going to change significantly soon) https://github.com/GBLS/docassemble-MAEvictionDefense/blob/main/docassemble/MAEvictionDefense/data/templates/CoverLetter.docx

**Comment by ianeis** [comment]
information_collected.yml contains variables used in next steps document

**Comment by ianeis** [comment]
Move formatting from .yml into document

**Comment by ianeis** [comment]
Generate next steps document for feedback

**Comment by ianeis** [comment]
[eviction_helper_next_steps.pdf](https://github.com/nonprofittechy/docassemble-MOHUDEvictionProject/files/10826840/eviction_helper_next_steps.pdf)

Sample next steps document.

**Comment by ianeis** [comment]
Attached document above is as generated by interview
