### ISSUE TITLE
trial_court error 

### ISSUE THREAD

**Issue by miabonardi** [nonprofittechy/docassemble-MOHUDEvictionProject#168]
KeyError: None In line: trial_court.classification = county_dictionary[trial_court.county][‘class’]

[Error.pdf](https://github.com/nonprofittechy/docassemble-MOHUDEvictionProject/files/11305271/Error.pdf)

**Comment by tobyfey** [comment]
I fixed this bug, but the bigger issue is how to deal with counties/addresses that aren't recognized.  After I fixed this, trial_court.classification is set to None, which means the question about property sales defaults to the "not equal to 1", non-first class county standard, when I'm guessing more people are probably in first class counties but at the very least, it seems like it should be clear that the county is not known and what kind of information is given.
