### ISSUE TITLE
Add capitalize() function to user and landlord names

### ISSUE THREAD

**Issue by miabonardi** [nonprofittechy/docassemble-MOHUDEvictionProject#179]
Higher priority to add to docs, lower priority to add throughout interview

**Comment by nonprofittechy** [comment]
Counterpoint - Not all last names should have an initial capital letter. For example, many Dutch surnames start with "van" which should be lower case.

If we change the capitalization of someone's name we should offer it to the person to verify capitalization. See: https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/

**Comment by miabonardi** [comment]
> Counterpoint - Not all last names should have an initial capital letter. For example, many Dutch surnames start with "van" which should be lower case.
> 
> If we change the capitalization of someone's name we should offer it to the person to verify capitalization. See: https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/

Fantastic point! I'll share with Chris
