### ISSUE TITLE
Ask if attorney, tenant or helper

### ISSUE THREAD

**Issue by nonprofittechy** [nonprofittechy/docassemble-MOHUDEvictionProject#19]

**Comment by tobyfey** [comment]
What do we want to do with this information?  Change questions from "You" to "The Defendant"?  Add options only for attorneys, like e-filing?

**Comment by nonprofittechy** [comment]
I suggest asking if the pleadings will be ghostwritten or filed on the tenants behalf and change the signature block to match. We should also consider changing you/the tenant language to match

**Comment by nonprofittechy** [comment]
I like how we do this in the housing code checklist project: https://github.com/nonprofittechy/docassemble-HousingCodeChecklist/blob/fa54f6bc11776eb0490f211b7a30b85016d93d26/docassemble/HousingCodeChecklist/data/questions/customized_screens.yml#L13

**Comment by tobyfey** [comment]
Added the question from housing checklist and using `person_answering` to gather users[0].name.first.  Do we want to replace every use of "you"?  Also need to change signature.  Also could make an attorney input screen?
