### ISSUE TITLE
Loop payment attempt questions to support multiple payment attempts

### ISSUE THREAD

**Issue by ianeis** [nonprofittechy/docassemble-MOHUDEvictionProject#30]
Similar to how Docassemble asks for information for multiple Users.

The Answer would look something like: Defendant contacted Plaintiff via phone on October 6, 2022, communicating intent to pay the past-due rent in part. Plaintiff refused payment. Defendant contacted Plaintiff in person on October 7, 2022, communicating intent to pay the full amount of past-due rent. Plaintiff refused payment.

**Comment by tobyfey** [comment]
Terry thought it would be good to loop the payment information, but not to include the method, because it might not be helpful.  People usually say they tried to pay rent when they mean that they texted the landlord.
