### ISSUE TITLE
Opening screen--make MO specific, fix links and remove "project" as a descriptor

### ISSUE THREAD

**Issue by nonprofittechy** [nonprofittechy/docassemble-MOHUDEvictionProject#36]
![image](https://user-images.githubusercontent.com/7645641/196960173-ecfd66d2-588d-463d-8830-1324cf8dd204.png)

**Comment by tobyfey** [comment]
![Screenshot from 2022-12-09 13-31-39](https://user-images.githubusercontent.com/7644783/206769100-b5dea99a-ba62-40bc-8a72-9d6220c0479f.png)
