### ISSUE TITLE
Make the second intro screen clearer -- clarify we will produce documents. simplify language. specify (examples) of what someone needs before they start

### ISSUE THREAD

**Issue by nonprofittechy** [nonprofittechy/docassemble-MOHUDEvictionProject#37]
![image](https://user-images.githubusercontent.com/7645641/196960426-1a0f96a6-b2dc-4a16-9336-4567455ac058.png)

**Comment by tobyfey** [comment]
![Screenshot from 2022-12-09 13-35-04](https://user-images.githubusercontent.com/7644783/206769589-750c629c-31e5-417f-aea8-242ec78c1df7.png)
