### ISSUE TITLE
Consistent language - filing date vs date stamp

### ISSUE THREAD

**Issue by nonprofittechy** [nonprofittechy/docassemble-MOHUDEvictionProject#41]
![image](https://user-images.githubusercontent.com/7645641/196962342-af3fea5f-e80e-4f7f-bce0-c03afdf466d2.png)

**Comment by tobyfey** [comment]
![Screenshot from 2022-12-09 13-40-22](https://user-images.githubusercontent.com/7644783/206770492-0369aba6-0008-4032-9563-af97c651ec80.png)
