### ISSUE TITLE
Change explanation language for additional plaintiffs

### ISSUE THREAD

**Issue by tobyfey** [nonprofittechy/docassemble-MOHUDEvictionProject#60]
id: names of opposing parties - petition

This explanation
`Your landlord is called the Plaintiff in an eviction case, and the Plaintiff’s name and address is near the top of the Caption on the left.`
doesn't seem to help for the second or additional plaintiff

maybe add language about why there would be a second plaintiff?

**Comment by nonprofittechy** [comment]
On the "there is another screen", ideally we could show a picture of the complaint with multiple plaintiffs.

**Comment by tobyfey** [comment]
language already changed to
 
 % if i >= 1:
  What is your ${ ordinal(i) } landlord's name?
  % else:
  What is your landlord's name?
  % endif
subquestion: |
  Look at the Summons and Petition, and write the name of the ${ ordinal(i) } "Plaintiff"
  exactly as it is written on the Summons and Petition.

tested and worked.

**Comment by tobyfey** [comment]
Fixed this.  When it asks if there is another Plaintiff, it still mentions the summons and petition even if you say you don't have it.
