### ISSUE TITLE
Think about placement of case.net questions

### ISSUE THREAD

**Issue by nonprofittechy** [nonprofittechy/docassemble-MOHUDEvictionProject#65]
We should decide if it's really necessary to invite user to search case.net to fill in some questions, and then decide when to prompt for that question. It's a major context switch to do early in the interview but several questions have versions with different language depending on access to case.net. Is it really necessary to have that extra check? Will it have different information than the Summons and Petition?

**Comment by tobyfey** [comment]
An attorney said that case.net will say if it was service by posting, to doublecheck.
