### ISSUE TITLE
Finish Review Screen

### ISSUE THREAD

**Issue by tobyfey** [nonprofittechy/docassemble-MOHUDEvictionProject#77]

**Comment by nonprofittechy** [comment]
There is a review screen generator in the Dashboard - might be useful. It usually needs a lot of cleanup.

The Dashboard is installed on interviews.lemmalegal.com

https://github.com/SuffolkLITLab/docassemble-ALDashboard/blob/main/docassemble/ALDashboard/data/questions/review_screen_generator.yml
