### ISSUE TITLE
ID any hearings: 
User feedback: bug
(`past_hearings`)

### ISSUE THREAD

**Issue by LemmaLegal** [nonprofittechy/docassemble-MOHUDEvictionProject#83]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `any hearings`
Details | Both the "Yes" and "No" options on this page take me to the same result "When is your eviction hearing"
Variable being sought | `past_hearings`
Package version | `1.0`
Maturity target | Level 1 - this needs to be fixed to be equivalent to the blank form
Filename | `docassemble.MOHUDEvictionProject:data/questions/MOHUDEvictionProject.yml`

**Comment by tobyfey** [comment]
So it asks if there is a past hearing and asks about the next scheduled hearing.
-Should there be an option for saying no hearing is scheduled?
-If the hearing is past, is it always that there are no more scheduled hearings?
-Should people file eviction answers after the hearing?

**Comment by tobyfey** [comment]
Duplicated in above issue
