### ISSUE TITLE
methods of summons not reflected in text for id: yep file an answer

### ISSUE THREAD

**Issue by LemmaLegal** [nonprofittechy/docassemble-MOHUDEvictionProject#99]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `Petition_introduction`
Details | 1. Switched from the introduction section to Should you file an Answer. 
2. Inputted that I did receive a copy of the summons for the lawsuit. 
3. Selected method of service used to deliver the summons (delivered by sheriff / it was delivered by the landlord or somebody other than the sheriff).  
4. Hit "next" and realized that the same prompt was given for my inputs about service (above) as the prompt following the selection for receiving the summons by mail: "You said that you got the Summons and Petition by mail..."
Variable being sought | `tenant_got_summons`
Package version | `1.0`
Maturity target | Level 2 - this needs to be fixed to meet expectations of a basic intake
Filename | `docassemble.MOHUDEvictionProject:data/questions/MOHUDEvictionProject.yml`

**Comment by tobyfey** [comment]
Changed labels for summons methods

  - "How did you get the Summons and Landlord's Petition?": method_of_summons_service
    datatype: radio
    choices:
      - "By mail": mail
      - "It was taped, stapled, or posted to my door or home": posting
      - "It was handed to you by the sheriff": sheriff
      - "It was handed to you by the landlord or somebody other than the sheriff": personal

Changed text for next screen id: yep file an answer

  % if tenant_got_summons:
  You said that you got the Summons and Petition by 
  % if method_of_summons_service in ['personal','sheriff']:
  personal delivery
  % else:
  mail
  % endif
  .
